dumps:
  path: '/media/n01z3/red3_2/learning_dumps/pneumo'
  weights: 'sota_weights'
  hard: 'hard_samples'
  logs: 'logs'
  predictions: '/mnt/ssd2/dataset/pneumo/predictions/sota_predictions'
  samples: 'samples'

dataset:
  path: '/mnt/ssd2/dataset/pneumo'
  images_dir: 'train_png'
  masks_dir: 'mask'
  test_dir: 'test_png'