dumps:
  path: '/mnt/hdd1/learning_dumps/pneumo'
  weights: 'weights'
  hard: 'hard_samples'
  logs: 'logs'
  predictions: '/mnt/hdd1/learning_dumps/pneumo/ext_predictions'
  samples: 'samples'

dataset:
  path: '/mnt/ssd1/datasets/pneumothorax_data/dataset1024'
  images_dir: 'train2'
  masks_dir: 'mask'
  test_dir: 'test2_png'