dumps:
  path: '/mnt/hdd1/learning_dumps/pneumo'
  weights: 'sota_weights'
  hard: 'hard_samples'
  logs: 'logs'
  predictions: '/mnt/ssd1/dataset/pneumo/fp32_d_predictions'
  samples: 'samples'

dataset:
  path: '/mnt/ssd1/dataset/pneumothorax_data/dataset1024'
  images_dir: 'train'
  masks_dir: 'mask'
  test_dir: 'test'