dumps:
  path: '/mnt/hdd2/learning_dumps/pneumo'
  weights: 'weights'
  hard: 'hard_samples'
  logs: 'logs'
  predictions: 'predictions'
  samples: 'samples'

dataset:
  path: '/mnt/ssd1/dataset/pneumothorax_data'
  images_dir: 'train2_png'
  masks_dir: 'mask'
  test_dir: 'test2_png'